apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders-service
    app-group: microservices-orders
spec:
  selector:
    app: orders-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 18894
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
        app-group: microservices-orders
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
      - name: shared-client-config-volume
        configMap:
          name: cc.shared-client-config
      - name: sasl-jaas-config-volume
        secret:
          secretName: cc.sasl-jaas-config.microservices-orders-client.kafka-devops.microservices-orders
      - name: bootstrap-config-volume
        secret:
          secretName: cc.bootstrap-servers.kafka-devops.microservices-orders
      - name: schema-registry-basic-user-info-config-volume
        secret:
          secretName: cc.schema-registry-basic-auth-user-info.kafka-devops-sr-client.kafka-devops
      - name: schema-registry-url-volume
        secret:
          secretName: cc.schema-registry-url.kafka-devops
      containers:
      - name: orders-service
        image: cnfldemos/orders-service:sha-82165db
        env:
        - name: STARTUP_DELAY
          value: "0"
        volumeMounts:
        - name: shared-client-config-volume
          mountPath: /etc/config/orders-service/application-shared-client.properties
          subPath: application-shared-client.properties
          readOnly: true
        - name: sasl-jaas-config-volume
          mountPath: /etc/config/orders-service/application-sasl-jaas-config.properties
          subPath: application-sasl-jaas-config.properties
          readOnly: true
        - name: bootstrap-config-volume
          mountPath: /etc/config/orders-service/application-bootstrap-servers.properties
          subPath: application-bootstrap-servers.properties
          readOnly: true
        - name: schema-registry-basic-user-info-config-volume
          mountPath: /etc/config/orders-service/application-schema-registry-basic-auth-user-info.properties
          subPath: application-schema-registry-basic-auth-user-info.properties
          readOnly: true
        - name: schema-registry-url-volume
          mountPath: /etc/config/orders-service/application-schema-registry-url.properties
          subPath: application-schema-registry-url.properties
          readOnly: true
        ports:
        - containerPort: 18894

