apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders-service
    app-group: microservices-orders
spec:
  selector:
    app: orders-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 18894
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
        app-group: microservices-orders
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
      - name: shared-client-config-volume
        configMap:
          name: cc.shared-client-config
      - name: sasl-jaas-config-volume
        secret:
          secretName: cc.sasl-jaas-config.microservices-orders-client.streaming-ops-dev.microservices-orders
      - name: bootstrap-config-volume
        secret:
          secretName: cc.bootstrap-servers.streaming-ops-dev.microservices-orders
      - name: schema-registry-basic-user-info-config-volume
        secret:
          secretName: cc.schema-registry-basic-auth-user-info.streaming-ops-sr-client.streaming-ops-dev
      - name: schema-registry-url-volume
        secret:
          secretName: cc.schema-registry-url.streaming-ops-dev
      containers:
      - name: orders-service
        image: cnfldemos/orders-service:sha-0ccce99 # 10.0.8
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "bootstrap-servers,sasl-jaas-config,schema-registry-basic-auth-user-info,schema-registry-url,shared-client"
        - name: STARTUP_DELAY
          value: "0"
        volumeMounts:
        - name: shared-client-config-volume
          mountPath: /workspace/config/application-shared-client.properties
          subPath: shared-client.properties
          readOnly: true
        - name: sasl-jaas-config-volume
          mountPath: /workspace/config/application-sasl-jaas-config.properties
          subPath: sasl-jaas-config.properties
          readOnly: true
        - name: bootstrap-config-volume
          mountPath: /workspace/config/application-bootstrap-servers.properties
          subPath: bootstrap-servers.properties
          readOnly: true
        - name: schema-registry-basic-user-info-config-volume
          mountPath: /workspace/config/application-schema-registry-basic-auth-user-info.properties
          subPath: schema-registry-basic-auth-user-info.properties
          readOnly: true
        - name: schema-registry-url-volume
          mountPath: /workspace/config/application-schema-registry-url.properties
          subPath: schema-registry-url.properties
          readOnly: true
        ports:
        - containerPort: 18894
        startupProbe:
          httpGet:
            path: /v1/healthcheck
            port: 18894
          failureThreshold: 12
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /v1/healthcheck
            port: 18894
          initialDelaySeconds: 3
          periodSeconds: 30




