apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  template:
    spec:
      containers:
      - name: orders-service
        image: cnfldemos/orders-service:sha-f534834 # 10.0.4

