apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  template:
    spec:
      containers:
      - name: orders-service
        image: cnfldemos/orders-service:sha-109abbf
        args: ["--logging.level.root=DEBUG"]

