name: Release microservices-orders-connect Image

on:
  push:
    branches:
    - master
    paths:
    - 'images/connect/**'
  workflow_dispatch:

jobs:
  build:
    name: Release microservices-orders-connect Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: images/connect
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=cnfldemos/microservices-orders-connect
          SHA=$(git log -1 --pretty=%h)
          TAGS="${DOCKER_IMAGE}:sha-${SHA}"
          echo ::set-output name=tags::${TAGS}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: images/connect/
          file: images/connect/Dockerfile
          push: false # to true before releasing changes
          tags: ${{ steps.prep.outputs.tags }}

